#!/usr/bin/env bash

OLD_HOSTNAME="$( hostname )"
NEW_HOSTNAME="$1"

if [ -z "$NEW_HOSTNAME" ]; then
 echo -n "Introduza o novo hostname: "
 read NEW_HOSTNAME < /dev/tty
fi

if [ -z "$NEW_HOSTNAME" ]; then
 echo "Erro. Hostname incorrecto ou em falta. A sair..."
 exit 1
fi

echo "A alterar hostname de $OLD_HOSTNAME para $NEW_HOSTNAME..."

hostnamectl set-hostname $NEW_HOSTNAME
hostnamectl set-hostname $NEW_HOSTNAME --static
hostnamectl set-hostname $NEW_HOSTNAME --transient

sed -i "s/HOSTNAME=.*/HOSTNAME=$NEW_HOSTNAME/g" /etc/sysconfig/network

if [ -n "$( grep "$OLD_HOSTNAME" /etc/hosts )" ]; then
 sed -i "s/$OLD_HOSTNAME/$NEW_HOSTNAME/g" /etc/hosts
else
 echo -e "$( hostname -I | awk '{ print $1 }' )\t$NEW_HOSTNAME" >> /etc/hosts
fi

echo "Concluido com sucesso. Reinicie o sistema!"
